# config.toml

[general]
threshold = 0.005
wallet_address = "0x1234567890abcdef1234567890abcdef12345678"
web3_provider = "https://mainnet.infura.io/v3/YOUR-PROJECT-ID"

[tokens]
borrow_token = "USDT"
deposit_token = "DAI"
